const fs = require('fs');
const path = require('path');
const loaderUtils = require('loader-utils');

const headerMessage = '// This file is automatically generated.\n// Please do not change this file!'
 
const getTypingFilePath = (filePath) => {
    const dirPath = path.dirname(filePath)
    const fileName = path.basename(filePath)

    return path.join(dirPath, `${fileName}.d.ts`)
}

const moduleToInterface = (moduleKeys) => {
   const interfaceFields = moduleKeys
    .sort()
    .map(key => `export const ${key}: any;`)
    .join('\n') 

    return interfaceFields
}

module.exports = function (content, ...rest) {
    const filePath = this.resourcePath

    const options = loaderUtils.getOptions(this) || {}

    const typingFilePath = getTypingFilePath(filePath)

    const regex = /\["([^\\"]+)"\]/g
    let match
    let moduleKeys = new Set()

    while(match = regex.exec(content)) {
        moduleKeys.add(match[1])
    }
    moduleKeys = [...moduleKeys]

    const moduleDefinition = `${headerMessage}\n${moduleToInterface(moduleKeys)}`

    fs.writeFile(typingFilePath, moduleDefinition, { encoding: 'utf-8' })

    return content
}